Repository RichardPompeo/personspace, pull requests merged in 2023-07, with the labels that each got.

#17 feat: added notification components and perfil button
  apps/web/components/SignInModal.tsx
  apps/web/components/SignUpModal.tsx
  apps/web/components/UtilityContent.tsx
  apps/web/contexts/AuthProvider.tsx
  apps/web/languages/en.json
  apps/web/languages/pt.json
  apps/web/styles/components/ModalStyles.ts
  apps/web/styles/components/UtilityStyles.ts
  apps/web/utils/notifications.tsx
  packages/ui/buttons/IconButton.ts
  packages/ui/buttons/PrimaryButton.tsx
  packages/ui/buttons/PrimaryButtonStyle.ts
  packages/ui/buttons/SecondaryButton.tsx
  packages/ui/buttons/SecondaryButtonStyle.ts
Labels: default

#19 feat: add notification components
  apps/web/components/SignInModal.tsx
  apps/web/components/SignUpModal.tsx
  apps/web/components/UtilityContent.tsx
  apps/web/contexts/AuthProvider.tsx
  apps/web/languages/en.json
  apps/web/languages/pt.json
  apps/web/styles/components/ModalStyles.ts
  apps/web/styles/components/UtilityStyles.ts
  apps/web/utils/notifications.tsx
  packages/ui/buttons/IconButton.ts
  packages/ui/buttons/PrimaryButton.tsx
  packages/ui/buttons/PrimaryButtonStyle.ts
  packages/ui/buttons/SecondaryButton.tsx
  packages/ui/buttons/SecondaryButtonStyle.ts
Labels: qa

#24 feat annotations page
  apps/backend/prisma/schema.prisma
  apps/backend/schema.gql
  apps/backend/src/dtos/inputs/CreateNoteInput.ts
  apps/backend/src/dtos/inputs/DeleteNoteInput.ts
  apps/backend/src/dtos/inputs/UpdateNoteInput.ts
  apps/backend/src/dtos/models/NoteModel.ts
  apps/backend/src/resolvers/NotesResolver.ts
  apps/backend/src/resolvers/UserResolver.ts
  apps/backend/src/server.ts
  apps/web/app/HomeStyles.ts
  apps/web/app/layout.tsx
  apps/web/app/notes/NotesStyle.ts
  apps/web/app/notes/page.tsx
  apps/web/app/page.tsx
  apps/web/components/app/Modal.tsx
  apps/web/components/app/ModalStyles.ts
  apps/web/components/app/Navbar.tsx
  apps/web/components/app/NavbarStyles.ts
  apps/web/components/app/UtilityContent.tsx
  apps/web/components/app/UtilityStyles.ts
  apps/web/components/notes/CreateNote.tsx
  apps/web/components/notes/CreateNoteStyles.ts
  apps/web/components/notes/Note.tsx
  apps/web/components/notes/NoteStyles.ts
  apps/web/components/sign-in/SignInModal.tsx
  apps/web/components/sign-up/SignUpModal.tsx
  apps/web/contexts/AuthProvider.tsx
  apps/web/graphql/createNoteMutation.ts
  apps/web/graphql/deleteNoteMutation.ts
  apps/web/graphql/getNotesQuery.ts
  apps/web/graphql/updateNoteMutation.ts
  apps/web/languages/en.json
  apps/web/languages/pt.json
  apps/web/layout/LayoutStyles.ts
  apps/web/layout/index.tsx
  apps/web/package.json
  packages/ui/buttons/IconButton.ts
  packages/ui/buttons/PrimaryButtonStyle.ts
  yarn.lock
Labels: development
